version: '3.3'
services:
  my-nuxt-app:
    build: .
    container_name: nuxt-app
    restart: unless-stopped
    ports:
      - 3000:3000
    labels:
      - coolify.managed=true
      - coolify.applicationId=1
      - coolify.type=application
      - traefik.enable=true
      - traefik.http.routers.nuxt-app.rule=Host(`nuxt-app.hostspacecloud.com`)
      - traefik.http.routers.nuxt-app.entryPoints=http
      - traefik.http.services.nuxt-app.loadbalancer.server.port=3000