version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000"
    container_name: api-node
    labels:
      - traefik.enable=true
      - traefik.http.routers.api-node.rule=Host(`api-node.hostspacecloud.com`)
      - traefik.http.routers.api-node.entryPoints=http
      - traefik.http.services.api-node.loadbalancer.server.port=3000