spring.profiles.active: development
logging.level.org.springframework.cloud.kubernetes: DEBUG
message: hello default
management.server.port: 8081
---
spring.profiles: development
message: Java Spring App running on HCS
---
spring.profiles: kubernetes
message: hello kubernetes
